project:
  type: website

website:
  title: "Birds, Burns, & Bioacoustics"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: background.qmd
        text: Background

      - href: methods.qmd
        text: Methods & Data

      - text: Resources
        menu:
          - href: resources.qmd
            text: Overview

          - href: birdnet_guide.qmd
            text: BirdNET Guide

          - href: raven_guide.qmd
            text: Raven Guide
        
      - href: faq.qmd
        text: FAQ

format:
  html:
    theme: cosmo
    toc: true