---
title: "Birds, Burns & Bioacoustics 🔥🦅"
subtitle: "BIOL3007 — Semester 2 2026"
---

#### Welcome and thanks for joining project 3!

Please note that this repo is under active construction and files will be added throughout the semester.

NOTE: Technically it's **Ecoacoustics**, but then the alliteration is lost.

This is the home page of our repository! It contains information regarding your assignment in general. Use the navigation bar above to move through different pages to learn more about the study design, the methods you will learn over the next semester, and to find relevant resources such as code and recommended literature.

------------------------------------------------------------------------

## Research Project Information

### Aims and Background

The major aim of the project work is to allow you to design and execute a program of ecological research. Other objectives of the project are to complement the lecture course, to extend your experience of field and laboratory work from units such as BIOL2024 Ecology and Conservation, BIOL3009 Terrestrial Field Ecology or BIOL2022/2922 Biology experimental design & analysis (if you have done these units), and to allow you to work on living organisms in natural or manipulated environments.

By the time you begin your project, you should be familiar with concepts of experimental design in ecology, and of data collection and analysis. With this experience, you should be able to select a relevant ecological observation and to design methods of data collection and analysis to test hypotheses arising from models you have proposed to explain these observations (See Quinn, G.P. and Keough, M.J. (2002) Experimental Design and Data Analysis for Biologists, Cambridge University Press \[particularly chapters 1-3\]). Thus, the Ecology Research Project is designed to let you carry out a short-term program of research and to have the intellectual satisfaction of following up your own project ideas. Because the project extends over the semester, there is some flexibility in when you can carry out the study, but times should prioritise Wednesday labs and suit all group members.

Most of you, we hope, will want to test models and hypotheses arising from your own observations. For those wanting a starting point, we provide some project ideas, references, and background material (below). We encourage you to discuss any project topics with us during the first practical session. This will allow you to form project groups, help you to select a project you are particularly interested in, and help us in getting materials and equipment ready in good time!

Because the projects that you will be doing are new, there are no “right” or “wrong” results. However, if you begin with a clear aim and sound experimental design using a clear logical structure, you should be able to confidently interpret whatever findings you eventually obtain. Read published articles for how to design and structure an ecological study. e.g. Austral Ecology.

## Semester Timeline

| Week | Activity | Location |
|-------------------|---------------------------|---------------------------|
| 1 | Form project groups & develop ideas | Carslaw Wet Lab 301/302 |
| 2 | Groups finalise project ideas & approach | Carslaw Wet Lab 301/302 |
| 3 | Project work, draft presentations — **Project outline & Risk Assessment due Thurs 5pm** | Carslaw Wet Lab 301/302 *(Eleanor at conference but can be reached by email)* |
| 4 | **Group project presentations (assessed)** | Carslaw LT275 or Chemistry LT4 |
| 5 | Key ideas in ecology — discussion tutorials | Carslaw Wet Lab 301/302 |
| 6 | Self-directed project work — data collection | Carslaw Wet Lab 301/302 *OR* Online (decide with supervisors) |
| 7 | Key ideas in ecology (assessed, individual) — **written assessment due Mon 15 Sept 2026** | Carslaw LT275 or Chemistry LT4 |
| 8–10 | Self-directed project work — data collection | Meet with supervisor |
| 11 | Self-directed project work — results & analysis | Meet with supervisor |
| 12 | Self-directed work — summary & presentation prep | Meet with supervisor |
| 13 | **Group project presentations (assessed) — Peer Review due** | Carslaw LT275 or Chemistry LT4 |
| — | **Project report due — Sunday 8 Nov 2026, 11:59 pm (end of Week 13)** |  |

------------------------------------------------------------------------

## Contact

Questions or issues? Reach out via email —

-   Eleanor - **eleanor.hadfield\@sydney.edu.au**

-   Aaron - **aaron.greenville\@sydney.edu.au**

-   Glenda - **glenda.wardle\@sydney.edu.au**

#### Welcome and we hope you enjoy project 3!
